start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=0,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=0,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=4,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=4,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=8,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=8,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=0,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=4,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=8,ny=4,nny=16,sz=12,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=0,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=4,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Mirror,sx=12,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=8,nz=4,nnz=16
start "" run_sfseeder -u omniverse://localhost/Users/mike/SfBase.usda -n base1 -p matname=Red_Glass,sx=12,nx=4,nnx=16,sy=12,ny=4,nny=16,sz=12,nz=4,nnz=16